(function(){
'use strict';
const M=window.MonitorModel, $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=M.format;
const ICONS={chart:'M3 3v18h18M7 16v-4m5 4V8m5 8V5',briefcase:'M8 6V4h8v2M3 7h18v13H3zM3 11c5 4 13 4 18 0M10 12h4',settings:'M9 3h6l1 4 4 1v6l-4 1-1 5H9l-1-5-4-1V8l4-1zM15 11a3 3 0 1 0-6 0 3 3 0 0 0 6 0',bell:'M5 17h14l-2-3V9a5 5 0 0 0-10 0v5zM10 21h4M12 2v2',mail:'M3 5h18v14H3zM3 6l9 7 9-7',check:'m5 12 4 4L19 6',chevron:'m7 10 5 5 5-5',right:'m9 5 7 7-7 7',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14m5 12 6 6',refresh:'M20 7a9 9 0 1 0 1 8M20 2v6h-6',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18m0 4v6l4 2',folder:'M3 6h7l2 2h9v12H3z',pin:'M12 22s8-9 8-14A8 8 0 0 0 4 8c0 5 8 14 8 14m0-17a3 3 0 1 0 0 6 3 3 0 0 0 0-6',link:'m10 7 2-2a5 5 0 0 1 7 7l-2 2M14 17l-2 2a5 5 0 0 1-7-7l2-2m1 7 8-8',calendar:'M3 5h18v16H3zM7 2v6m10-6v6M3 10h18',info:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18m0 7v7m0-11v1',help:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18m-3 5a3 3 0 0 1 6 1c0 2-3 2-3 4m0 3v1',warning:'M12 3 2 21h20zM12 9v5m0 3v1',star:'m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',crown:'m3 6 5 5 4-7 4 7 5-5-2 13H5z',more:'M12 4v1m0 6v1m0 6v1',close:'m6 6 12 12M6 18 18 6',sliders:'M5 3v18M12 3v18M19 3v18M2 8h6m1 8h6m1-10h6',shield:'M12 2 3 6v6c0 6 9 10 9 10s9-4 9-10V6zM8 12l3 3 5-6',tag:'M3 3h9l9 9-9 9-9-9zM7 7h1',home:'m2 11 10-9 10 9M5 9v12h5v-7h4v7h5V9',layers:'m12 3 10 5-10 5L2 8zm-10 9 10 5 10-5M2 16l10 5 10-5',play:'m8 4 12 8-12 8z',arrow:'M4 12h16m-6-6 6 6-6 6',external:'M14 3h7v7m0-7L10 14M10 4H3v17h17v-7',document:'M5 2h9l5 5v15H5zM14 2v6h5M8 12h8M8 16h8',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12m13 0a3 3 0 1 0-6 0 3 3 0 0 0 6 0'};
function icon(name,cls=''){return `<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${ICONS[name]||ICONS.info}"/></svg>`;}
const KEY='webtronica-monitor-prototype-v1';
let state=M.createDemo(),pool={},page='dashboard',draft=M.clone(state.settings),expanded=new Set(),pageNumber=1,collecting=false,toastTimer,modalReturnFocus;
let filters={folder:'all',group:'all',url:'all',monitor:'all',tr:'all',search:'',from:'2026-09-01',to:'2026-09-27'};
const timers=new Map();
try{const raw=JSON.parse(localStorage.getItem(KEY));if(raw?.state?.version===1){state=raw.state;pool=raw.pool||{};draft=M.clone(state.settings);}}catch{}
function persist(){try{localStorage.setItem(KEY,JSON.stringify({state,pool}));}catch{}}
function getObject(id){return state.objects.find(o=>o.id===id);}
function tip(text){return `<button type="button" class="question" aria-label="Подсказка: ${esc(text)}" data-tip="${esc(text)}">?</button>`;}
function dev(title,body){return `<details class="dev"><summary>DEV — ${title}</summary><div class="dev-body">${body}</div></details>`;}
function badge(text,type='neutral',ico){return `<span class="badge ${type}">${ico?icon(ico):''}${text}</span>`;}
function description(o){return o.type==='group'?o.name:`Без группы · ${o.queries[0]?.url||'Нет URL'}`;}
function tooltipOff(){$('#tooltip').hidden=true;}
function toast(message,error=false){clearTimeout(toastTimer);const el=$('#toast');el.textContent=message;el.className='toast'+(error?' error':'');el.hidden=false;toastTimer=setTimeout(()=>el.hidden=true,4500);}
function opt(value,label,selected){return `<option value="${esc(value)}" ${String(value)===String(selected)?'selected':''}>${esc(label)}</option>`;}
function selectFilter(key,label,items,ico,wide=false){return `<div class="filter ${wide?'wide':''}">${ico?icon(ico):''}<div><label for="filter-${key}">${label}</label><select id="filter-${key}" data-filter="${key}">${items.map(x=>opt(x[0],x[1],filters[key])).join('')}</select></div></div>`;}
function help(){return `<details class="help-disclosure" id="how-it-works"><summary>${icon('info')} Как работает мониторинг позиций и текстовой релевантности ${icon('chevron','chevron')}</summary><div class="help-content">
<p><span class="step">01</span><strong>Проверка позиций.</strong><br>После каждого ручного или планового сбора проверяется доля запросов в заданном диапазоне, например не менее 60% в ТОП-10. Запросы «Без группы» объединяются в отдельные наборы по одинаковому Relevant URL.</p>
<p><span class="step">02</span><strong>Приоритетные запросы.</strong><br>Индивидуально контролируется снижение позиции, например на 3 и более позиции, если перед сбором запрос был в ТОП-20. Приоритетные запросы всегда участвуют в общей статистике Группы.</p>
<p><span class="step">03</span><strong>Главный запрос.</strong><br>Автоматически выбирается запрос с максимальной !точной частотностью. В обычной Группе его можно назначить вручную. Для «Без группы» выбор всегда автоматический внутри одного Relevant URL.</p>
<p><span class="step">04</span><strong>Анализ текстовой релевантности.</strong><br>При нарушении хотя бы одного условия создаётся уведомление Webtronica. TR запускается автоматически по Главному запросу и его Relevant URL или вручную SEO-специалистом — в зависимости от настроек.</p>
<p><span class="step">05</span><strong>Оценка TR.</strong><br>Общая релевантность = (Ширина + Глубина) / 2. Все три показателя сравниваются с целями и непосредственно предыдущим анализом. Для самого первого анализа динамика не рассчитывается.</p>
<p><span class="step">06</span><strong>Повторные проверки.</strong><br>Каждый сбор — самостоятельная контрольная точка. Если условие снова нарушено, создаётся новое событие и выполняется сценарий TR. Два условия в одном сборе — одно событие и один запуск на объект.</p></div></details>`;}
function shell(content){const unread=state.events.filter(e=>!e.read).length;return `<aside class="sidebar" aria-label="Главная навигация"><div class="brand" title="Webtronica"><svg viewBox="0 0 40 48" fill="none" stroke="currentColor" stroke-width="4"><path d="M20 3 36 14v21L20 45 4 35V14Zm0 0v42M4 14l8 5m16 0 8-5M4 35l8-5m16 0 8 5"/></svg></div><span class="side-item" title="Проекты">${icon('briefcase')}</span><span class="side-item" title="Семантическое ядро">${icon('layers')}</span><span class="side-item" title="Отчёты">${icon('document')}</span><button class="side-item ${page!=='settings'?'active':''}" data-nav="dashboard" aria-label="Монитор позиций">${icon('chart')}</button><button class="side-item ${page==='settings'?'active':''}" data-nav="settings" aria-label="Настройки проекта">${icon('settings')}</button><span class="side-item" title="Инструменты">${icon('sliders')}</span><span class="side-item" title="Контроль сайта">${icon('shield')}</span><div class="sidebar-bottom"><button class="side-item" data-action="demo" aria-label="Демонстрационные сценарии">${icon('play')}</button></div></aside>
<header class="topbar"><div class="account">Юзер ${icon('chevron')}</div><div class="project-select">${icon('briefcase')}<div class="grow"><div class="label">Проект</div><strong>don-gabion.ru</strong></div>${icon('chevron')}</div><span class="all-projects muted">Все проекты</span><div class="top-right"><span class="demo-label">HTML-прототип</span><button class="icon-btn notifications-button" data-action="notifications" aria-label="Уведомления Webtronica">${icon('bell')}${unread?`<span class="counter">${unread}</span>`:''}</button><span class="icon-btn" title="Сообщения">${icon('mail')}</span><span class="email">webtronyata@webtronics.ru</span><span class="avatar" title="SEO-специалист">WT</span>${icon('chevron')}</div></header>
<main class="main"><nav class="breadcrumbs" aria-label="Хлебные крошки"><span class="purple">Проекты</span><span>·</span><span class="purple">don-gabion.ru</span><span>·</span><button class="link-button" data-nav="${page==='settings'?'settings':'dashboard'}">${page==='settings'?'Настройки проекта':'Монитор позиций'}</button><span>·</span><span>${page==='settings'?'Мониторинг позиций и TR':page==='positions'?'Позиции':'Просадки и релевантность'}</span></nav>${content}<div class="demo-footer"><span>Демонстрационные данные · don-gabion.ru · изменения сохраняются в этом браузере</span><button class="link-button" data-action="demo">Сценарии прототипа ${icon('right')}</button></div></main><button class="help-float" data-action="help" aria-label="Как работает мониторинг">${icon('help')}</button>`;}
function navigation(){return `<div class="page-heading"><div class="heading-left"><h1>Монитор позиций</h1>${badge(state.settings.enabled?'Мониторинг включён':'Мониторинг выключен',state.settings.enabled?'green':'neutral')}</div><div class="flex"><button class="btn outline" data-nav="settings">${icon('settings')} Настройки мониторинга</button><button class="btn primary" data-action="collect" ${collecting?'disabled':''}>${icon('refresh',collecting?'spin':'')}${collecting?'Сбор позиций…':'Собрать позиции'}</button></div></div><nav class="tabs" aria-label="Разделы монитора"><button class="tab ${page==='positions'?'active':''}" data-nav="positions">Позиции</button><button class="tab ${page==='dashboard'?'active':''}" data-nav="dashboard">Просадки и релевантность <span class="badge ${state.settings.enabled?'orange':'neutral'}">${state.objects.filter(o=>M.evaluate(o,state.settings).violated).length}</span></button></nav>${help()}`;}
function filterbar(){const groups=[['all','Все группы'],...state.objects.filter(o=>o.type==='group').map(o=>[o.id,o.name]),['ungrouped','Без группы']];const urls=[...new Set(state.objects.flatMap(o=>o.queries.map(q=>q.url)))];return `<div class="filterbar"><div class="filter" style="flex:.7"><span class="engine-dot">Я</span><div><label for="context-engine">Поисковая система</label><select id="context-engine" data-context="engine">${['Яндекс','Google'].map(x=>opt(x,x,state.context.engine)).join('')}</select></div></div><div class="filter wide">${icon('pin')}<div><label for="context-region">Регион</label><select id="context-region" data-context="region">${['Санкт-Петербург','Москва'].map(x=>opt(x,x,state.context.region)).join('')}</select></div></div>${selectFilter('folder','Папка',[['all','Все папки'],['Каталог','Каталог'],['Услуги','Услуги'],['Без папки','Без папки']],'folder')}${selectFilter('group','Группа',groups,null,true)}${selectFilter('url','Relevant URL',[['all','Все URL'],...urls.map(u=>[u,u])],'link',true)}<div class="filter period">${icon('calendar')}<div><label>Период проверки</label><div class="flex" style="gap:3px"><input type="date" aria-label="Начало периода" data-filter="from" value="${filters.from}"><span class="muted">—</span><input type="date" aria-label="Конец периода" data-filter="to" value="${filters.to}"></div></div></div></div>`;}
function parseDate(date){if(!date)return '';const a=date.slice(0,10).split('.');return `${a[2]}-${a[1]}-${a[0]}`;}
function filteredObjects(){return state.hasPositions===false?[]:state.objects.filter(o=>{const c=M.evaluate(o,state.settings);const t=M.trStatus(o,state.settings);const date=parseDate(o.lastCheck||state.lastCollection);const text=`${o.name} ${o.queries.map(q=>`${q.text} ${q.url}`).join(' ')}`.toLowerCase();return (filters.folder==='all'||o.folder===filters.folder)&&(filters.group==='all'||(filters.group==='ungrouped'?o.type==='ungrouped':filters.group===o.id))&&(filters.url==='all'||o.queries.some(q=>q.url===filters.url))&&(!filters.search||text.includes(filters.search.toLowerCase()))&&(!filters.from||date>=filters.from)&&(!filters.to||date<=filters.to)&&(page==='positions'||((filters.monitor==='all'||(state.settings.enabled&&(filters.monitor==='violated'?c.violated:!c.violated)))&&(filters.tr==='all'||(filters.tr==='running'?o.trState==='running':t===filters.tr))));});}
function summary(){const objects=state.hasPositions===false?[]:state.objects;const q=objects.flatMap(o=>o.queries).filter(q=>q.priority);const inZone=q.filter(q=>q.previous!==null&&q.previous<=state.settings.priorityTop).length;return `<section class="summary-strip" aria-label="Сводка по всему проекту"><div class="summary-item"><div class="summary-label">Объектов мониторинга ${tip('Все Группы и отдельные наборы запросов «Без группы» по Relevant URL. Сводка относится ко всему проекту в выбранной ПС и регионе.')}</div><div class="summary-value">${objects.length}</div><div class="summary-note">${objects.filter(o=>o.type==='group').length} групп · ${objects.filter(o=>o.type==='ungrouped').length} набора без группы</div></div><div class="summary-item"><div class="summary-label">Условия нарушены</div><div class="summary-value orange">${state.settings.enabled?objects.filter(o=>M.evaluate(o,state.settings).violated).length:'—'}</div><div class="summary-note">${state.settings.enabled?'по результатам позиций':'мониторинг выключен'}</div></div><div class="summary-item"><div class="summary-label">TR ниже цели</div><div class="summary-value orange">${objects.filter(o=>M.trStatus(o,state.settings)==='below').length}</div><div class="summary-note">${objects.filter(o=>o.trState==='running').length} анализов в работе</div></div><div class="summary-item"><div class="summary-label">Приоритетные запросы</div><div class="summary-value">${q.length}</div><div class="summary-note">${state.settings.priorities?`в зоне ТОП-${state.settings.priorityTop}: ${inZone}`:'индивидуальный контроль выключен'}</div></div><div class="summary-item"><div class="summary-label">За пределами зоны ${tip('Зона индивидуального контроля определяется по позиции перед текущим сбором. Все эти запросы продолжают участвовать в общей статистике Группы.')}</div><div class="summary-value muted">${state.settings.priorities?q.length-inZone:'—'}</div><div class="summary-note">${state.settings.priorities?`до сбора — ниже ТОП-${state.settings.priorityTop}`:'участвуют в статистике группы'}</div></div></section>`;}
function conditions(){const s=state.settings;return `<div class="conditions"><div class="condition-text">${icon('shield')}<span>Контроль: <strong>≥${s.percent}% в ТОП-${s.top}</strong></span>${s.priorities?`<span class="separator">/</span><span>приоритетные: <strong>снижение ≥${s.drop}, из ТОП-${s.priorityTop}</strong></span>`:''}<span class="separator">/</span><span>TR: <strong>${s.mode==='auto'?'автоматически':'вручную'}</strong></span></div><span>Последний сбор: ${state.lastCollection||'—'}</span></div>`;}
function empty(){return `<div class="empty">${icon('search')}<h3>${state.hasPositions===false?'В выбранной ПС и регионе пока нет позиций':'По выбранным фильтрам ничего не найдено'}</h3><p>${state.hasPositions===false?'Нажмите «Собрать позиции», чтобы получить демонстрационные данные.':'Измените условия поиска или сбросьте фильтры.'}</p>${state.hasPositions===false?'':`<button class="btn text" data-action="reset-filters">Сбросить фильтры</button>`}</div>`;}
function searchToolbar(){return `<div class="table-toolbar"><label class="searchbox">${icon('search')}<input type="search" placeholder="${page==='positions'?'Поиск запроса':'Поиск группы, URL или запроса'}" aria-label="Поиск" id="search" value="${esc(filters.search)}"></label><div class="toolbar-filters">${page==='dashboard'?`<select aria-label="Состояние мониторинга" data-filter="monitor">${[['all','Все состояния позиций'],['ok','Условие выполнено'],['violated','Условие нарушено']].map(x=>opt(...x,filters.monitor)).join('')}</select><select aria-label="Состояние TR" data-filter="tr">${[['all','Все состояния TR'],['ok','Соответствует цели'],['below','Ниже цели'],['none','Анализ не выполнен'],['running','Анализ выполняется']].map(x=>opt(...x,filters.tr)).join('')}</select>`:`<span class="legend"><span>${icon('crown')} Главный запрос</span><span>${icon('star')} Приоритетный</span></span>`}<button class="icon-btn" data-action="reset-filters" aria-label="Сбросить фильтры" title="Сбросить фильтры">${icon('refresh')}</button></div></div>`;}
function trCell(o){const s=M.trStatus(o,state.settings),result=o.analyses.at(-1);return `${badge(s==='ok'?'Соответствует цели':s==='below'?'Ниже цели':'Анализ не выполнен',s==='ok'?'green':s==='below'?'orange':'neutral',s==='ok'?'check':s==='below'?'warning':null)}${result?`<div class="tr-score">${fmt(M.total(result))}<span class="muted"> / 100</span> ${tip(`Общая ${fmt(M.total(result))} · Ширина ${result.width} · Глубина ${result.depth}. Цели: ≥${state.settings.general} / ≥${state.settings.width} / ≥${state.settings.depth}.`)}</div>`:''}`;}
function splitButton(o){const running=o.trState==='running',main=M.mainQuery(o),need=o.needsAnalysis||!o.analyses.length;const blocked=!main;const style=running?'outline':need?'orange-btn':'primary';return `<div class="split"><button class="btn ${style}" data-action="${running?'noop':need?'run-tr':'open-tr'}" data-id="${o.id}" ${running||blocked?'disabled':''} ${need&&!running&&!blocked?'data-tip="После последнего сбора позиций выполнено условие мониторинга. Рекомендуется выполнить новый анализ текстовой релевантности."':''}>${icon(running?'refresh':blocked?'warning':need?'warning':'external',running?'spin':'')}${running?'Анализ TR выполняется…':blocked?'Нет Главного запроса':need?'Запустить анализ TR':'Открыть анализ TR'}</button><button class="btn drop-btn ${style}" data-action="tr-menu" data-id="${o.id}" aria-label="Действия TR: ${esc(description(o))}" aria-haspopup="menu">${icon('chevron')}</button></div>${o.queue.length?`<span class="secondary">В очереди: ${o.queue.length}</span>`:''}`;}
function mainCell(o){const q=M.mainQuery(o);return q?`${esc(q.text)}<span class="secondary">${o.manualMain?`${icon('crown')} Выбран вручную`:'Автоматический выбор'}</span>`:`<button class="local-warning" data-action="missing" data-id="${o.id}">${icon('warning')}<span>Нет !точной частотности</span></button>`;}
function objectRow(o){const c=M.evaluate(o,state.settings),open=expanded.has(o.id);return `<tr class="object-row ${open?'expanded':''}" data-row="${o.id}"><td class="expand-cell"><button class="icon-btn" data-action="expand" data-id="${o.id}" aria-label="Подробности: ${esc(description(o))}" aria-expanded="${open}">${icon(open?'chevron':'right')}</button></td><td><button class="link-button object-name" data-action="expand" data-id="${o.id}" style="color:var(--ink)">${esc(o.name)}</button><span class="object-kind">${o.type==='group'?'Группа':'Набор по URL'} · ${c.count} запросов</span></td><td><button class="link-button url" data-action="filter-url" data-url="${esc(M.mainQuery(o)?.url||o.queries[0]?.url)}">${esc(M.mainQuery(o)?.url||o.queries[0]?.url)}</button></td><td><div class="position-number ${state.settings.enabled&&c.groupFailed?'orange':state.settings.enabled?'green':'muted'}">${fmt(c.percent)}% <span class="small" style="font-weight:400">в ТОП-${state.settings.top}</span></div><div class="bar ${c.groupFailed?'warning':''}"><span style="width:${c.percent}%"></span></div></td><td class="reason">${!state.settings.enabled?'<span class="muted">Контроль выключен</span>':!c.violated?`<span class="green">${icon('check')} Условие выполнено</span>`:`${c.groupFailed?`<span class="orange">Требуется ≥${state.settings.percent}%</span>`:''}${c.drops.length?`<span class="${c.groupFailed?'secondary':'orange'}">${c.drops.length} приоритетн. −${state.settings.drop}+</span>`:''}`}</td><td class="query-cell">${mainCell(o)}</td><td>${trCell(o)}</td><td><span class="small nowrap">${o.lastCheck?.slice(0,10)||'—'}</span><span class="secondary">${o.lastCheck?.slice(11)||''}</span></td><td>${splitButton(o)}</td></tr>${open?`<tr class="detail-row"><td colspan="9">${detailsContent(o)}</td></tr>`:''}`;}
function delta(v,prev){if(prev===null)return '<span class="muted">—</span>';const d=v-prev;return `<span class="${d>0?'green':d<0?'red':'muted'}">${d>0?'↑ +':d<0?'↓ −':''}${fmt(Math.abs(d))}</span>`;}
function trTable(o,index=o.analyses.length-1){const r=o.analyses[index],p=o.analyses[index-1];if(!r)return '<div class="neutral-note">Анализ ещё не выполнен. После первого замера здесь появятся показатели; динамика — со второго анализа.</div>';const rows=[['Общая релевантность',M.total(r),p?M.total(p):null,state.settings.general],['Ширина',r.width,p?p.width:null,state.settings.width],['Глубина',r.depth,p?p.depth:null,state.settings.depth]];return `<table class="mini-table"><thead><tr><th>Показатель</th><th class="number">Предыдущий</th><th class="number">Сейчас</th><th class="number">Δ</th><th class="number">Цель</th></tr></thead><tbody>${rows.map(([label,v,prev,target])=>`<tr><td>${label}</td><td class="number muted">${prev===null?'—':fmt(prev)}</td><td class="number"><strong>${fmt(v)}</strong></td><td class="number nowrap">${delta(v,prev)}</td><td class="number nowrap ${v>=target?'green':'orange'}">≥${target} ${v>=target?'✓':'⚠'}</td></tr>`).join('')}</tbody></table>${!p?'<p class="secondary">Первоначальный анализ. Предыдущего результата нет.</p>':''}`;}
function missingWarning(o){return `<div class="inline-warning"><div>${icon('warning')}</div><div><strong>Не определён Главный запрос</strong><br>Для автоматического определения Главного запроса необходимо заполнить поле «!точной» частотности.<br>${o.type==='group'?'Укажите частотность или назначьте Главный запрос вручную в таблице позиций.':'Для этого Relevant URL автоматический TR не выполняется до появления !точной частотности. Ручной выбор Главного запроса для «Без группы» недоступен.'}<br><button class="link-button" style="margin-top:5px" data-action="object-positions" data-id="${o.id}">Перейти к запросам ${icon('arrow')}</button></div></div>`;}
function detailsContent(o){const c=M.evaluate(o,state.settings);return `<div class="row-details">${!M.mainQuery(o)?`<div class="warning-detail">${missingWarning(o)}</div>`:''}<section><h3 class="detail-heading">${icon('chart')} Позиции</h3><div class="detail-stats"><span>Всего запросов</span><strong>${c.count}</strong><span>В ТОП-${state.settings.top}</span><strong>${c.inside} из ${c.count}</strong><span>Доля запросов</span><strong class="${c.groupFailed?'orange':'green'}">${fmt(c.percent)}%</strong><span>Целевое значение</span><strong>≥${state.settings.percent}%</strong></div><div class="priority-list">${c.drops.length?`<span class="small muted">Приоритетные запросы, вызвавшие сигнал</span>${c.drops.map(q=>`<div class="priority-item"><span>${icon('star')} ${esc(q.text)}</span><span class="nowrap orange">${q.previous} → ${q.position??'100+'} <span class="muted">(−${q.position===null?'∞':q.position-q.previous})</span></span></div>`).join('')}`:`<span class="muted">${state.settings.priorities?'Индивидуальных сигналов нет.':'Контроль приоритетных запросов выключен.'}</span>`}</div>${dev('условия объекта','<p>Источник: фактически собранные позиции актуального состава запросов. A: доля в целевом ТОПе ниже порога. B: приоритетный запрос был внутри порога <b>до сбора</b> и потерял не менее заданного числа позиций.</p><p>A ИЛИ B создаёт одно событие. Даже при выходе из ТОП-20 запрос участвует в общей статистике.</p>')}</section><section><h3 class="detail-heading">${icon('layers')} Текстовая релевантность</h3>${trTable(o)}<p class="secondary" style="margin-top:10px">${o.analyses.length?`Последний анализ: ${o.analyses.at(-1).date}`:'Нет результатов TR'}</p>${o.needsAnalysis?`<p class="secondary orange">${o.trState==='running'?'Новый анализ выполняется. Показаны предыдущие результаты.':'После сбора требуется новый анализ.'}</p>`:''}${dev('показатели TR','<p>Общая = (Ширина + Глубина) / 2, без промежуточного округления. Статус «Соответствует» — только когда достигнуты все три цели. Δ сравнивается непосредственно с предыдущим анализом. Первый замер не имеет Δ.</p><p>Событие создаёт нарушение позиций, результат TR дополнительных уведомлений не создаёт.</p>')}</section><section><h3 class="detail-heading">${icon('clock')} История проверок</h3>${history(o,3)}<button class="link-button small" style="margin-top:13px" data-action="history" data-id="${o.id}">Вся история (${o.checks.length}) ${icon('right')}</button>${dev('история и повторные сборы','<p>Неизменяемый снимок хранит collectionId, objectId, ПС, регион, состав, долю, порог и обе причины. Уникальный ключ события: collectionId + objectId в текущем контексте ПС/региона.</p><p>Следующий сбор с нарушением всегда создаёт новое событие и при автоматическом режиме новый TR. При текущем запуске он добавляется в очередь.</p>')}</section></div>`;}
function history(o,limit=100){return o.checks.length?`<div class="timeline">${o.checks.slice(0,limit).map(c=>`<div class="timeline-item"><div class="timeline-date">${c.date} · ${c.engine||'Яндекс'}</div><div class="timeline-status">${fmt(c.percent)}% запросов в ТОП-${c.top} · цель ≥${c.target}%</div><div class="${c.violated?'orange':'green'}">${c.violated?'Условие нарушено':'Условие выполнено'}</div>${c.reasons.map(r=>`<div>${esc(r)}</div>`).join('')}<div>${esc(c.tr)}</div></div>`).join('')}</div>`:'<p class="muted small">Проверки ещё не выполнялись.</p>';}
function dashboard(){const objects=filteredObjects();return `${navigation()}${filterbar()}${!state.settings.enabled?`<div class="status-strip">${icon('info')}Мониторинг выключен. Сбор позиций продолжает работать; условия не проверяются, события не создаются, TR автоматически не запускается.</div>`:''}${summary()}${conditions()}<section class="data-panel" aria-label="Просадки и релевантность">${searchToolbar()}<div id="table-content">${dashboardTable(objects)}</div></section>${dev('цикл мониторинга',`<p><b>Сбор → проверка условий → событие Webtronica → TR → сравнение с прошлым анализом и целями.</b> Источники: монитор позиций, !точная частотность, Главный запрос и Relevant URL. Контекст: выбранные ПС и регион. По умолчанию: ≥60% в ТОП-10; приоритетные — снижение ≥3 из ТОП-20; цели TR — 70 / 60 / 60.</p><p>Выключенный мониторинг не мешает сбору. Изменение состава Группы само по себе не создаёт событие мониторинга. Условие проверяется только на основании фактически собранных позиций актуального состава запросов.</p><p>Запросы «Без группы» объединяются только аналитически по Relevant URL — реальные Группы не создаются. Нет !точной частотности — локальное предупреждение, автоматический TR такого объекта пропускается. Частотность 0 допустима; при равенстве выбирается первый по стабильному ID.</p><p>Прототип использует локальные данные. Кнопка «Собрать позиции» имитирует успешный сбор. Ответы TR моделируются и не обращаются к внешним сервисам.</p>`)}`;}
function dashboardTable(objects){return `${objects.length?`<div class="table-scroll"><table class="data-table"><thead><tr><th></th><th>Объект</th><th>Relevant URL</th><th>Состояние позиций</th><th>Причина</th><th>Главный запрос</th><th>TR</th><th>Последняя проверка</th><th>Действия</th></tr></thead><tbody>${objects.map(objectRow).join('')}</tbody></table></div>`:empty()}<div class="table-footer"><span>Показано ${objects.length} из ${state.hasPositions===false?0:state.objects.length} объектов</span><span>Цели TR: общая ≥${state.settings.general} · ширина ≥${state.settings.width} · глубина ≥${state.settings.depth}</span></div>`;}
function positions(){return `${navigation()}${filterbar()}${conditions()}<section class="data-panel" aria-label="Таблица позиций">${searchToolbar()}<div id="table-content">${positionsTable()}</div></section>${dev('Главный и Приоритетный запрос',`<p>Главный выбирается по максимальной !точной частотности, включая нулевую. Если не все частотности известны, максимум не определён. В обычной Группе меню строки позволяет назначить запрос вручную и вернуть автовыбор. Ручное назначение фиксируется и не меняется при обновлении частотности.</p><p>Для «Без группы» — только автоматический выбор внутри Relevant URL. Звёздочка независимо включает приоритет. Главный и Приоритетный — разные признаки. Изменение этих признаков не создаёт уведомлений; они учитываются на следующем сборе.</p><p>Поля !точной частотности редактируемые. Пустое значение — отсутствуют данные. Отрицательные, дробные и нечисловые значения отклоняются. Выбор запроса не меняет историю уже выполненных анализов.</p>`)}`;}
function positionsTable(){const objects=filteredObjects();const all=objects.flatMap(o=>o.queries.filter(q=>!filters.search||`${q.text} ${q.url} ${o.name}`.toLowerCase().includes(filters.search.toLowerCase())).map(q=>({o,q})));const size=20,pages=Math.max(1,Math.ceil(all.length/size));pageNumber=Math.min(pageNumber,pages);const rows=all.slice((pageNumber-1)*size,pageNumber*size);return `${objects.length===1&&!M.mainQuery(objects[0])?`<div style="padding:14px">${missingWarning(objects[0])}</div>`:''}${rows.length?`<div class="table-scroll"><table class="data-table positions-table"><thead><tr><th style="width:48px">${icon('star')}</th><th>Запрос</th><th>Группа</th><th>Relevant URL</th><th class="end">!точная ${tip('По максимальной !точной частотности определяется Главный запрос. Нажмите на значение, чтобы изменить демонстрационные данные.')}</th><th class="end">Предыдущая</th><th class="end">${state.context.engine} · ${state.lastCollection?.slice(0,10)||'—'}</th><th></th></tr></thead><tbody>${rows.map(({o,q})=>{const main=M.mainQuery(o)?.id===q.id;return `<tr><td><button class="icon-btn priority-star ${q.priority?'selected':''}" data-action="priority" data-id="${o.id}" data-query="${q.id}" aria-label="Приоритетный: ${esc(q.text)}" aria-pressed="${q.priority}">${icon('star')}</button></td><td>${esc(q.text)}${main?`<span class="main-tag">${icon('crown')}Главный${o.manualMain?' · вручную':''}</span>`:''}</td><td><span class="group-label">${esc(o.name)}</span>${!M.mainQuery(o)?`<button class="local-warning" data-action="missing" data-id="${o.id}">${icon('warning')} Не определён Главный</button>`:''}</td><td><span class="url">${esc(q.url)}</span></td><td class="end"><input type="number" min="0" step="1" class="frequency-input" data-frequency="${q.id}" data-id="${o.id}" value="${q.frequency??''}" placeholder="—" aria-label="!точная частотность: ${esc(q.text)}"></td><td class="end muted mono">${q.previous??'—'}</td><td class="end mono"><strong>${q.position??'100+'}</strong><span class="position-change ${q.position<q.previous?'green':q.position>q.previous?'red':'muted'}">${q.position===q.previous?'—':`${q.position<q.previous?'↑':'↓'} ${Math.abs(q.position-q.previous)}`}</span></td><td><button class="icon-btn" data-action="query-menu" data-id="${o.id}" data-query="${q.id}" aria-label="Действия запроса: ${esc(q.text)}" aria-haspopup="menu">${icon('more')}</button></td></tr>`;}).join('')}</tbody></table></div>`:empty()}<div class="table-footer"><span>Запросы ${all.length?(pageNumber-1)*size+1:0}–${Math.min(pageNumber*size,all.length)} из ${all.length}</span><span class="pagination"><button class="btn" data-action="prev-page" ${pageNumber===1?'disabled':''} aria-label="Предыдущая страница">‹</button><span>Страница ${pageNumber} из ${pages}</span><button class="btn" data-action="next-page" ${pageNumber===pages?'disabled':''} aria-label="Следующая страница">›</button></span></div>`;}
function toggle(key,label){return `<div class="switch-row"><label class="switch"><input type="checkbox" data-setting="${key}" aria-label="${label}" ${draft[key]?'checked':''}><span class="switch-track"></span></label><span>${draft[key]?'Включено':'Выключено'}</span></div>`;}
function numberField(key,label,helpText,unit='',max=100){return `<div class="setting-field"><label for="setting-${key}">${label} ${tip(helpText)}</label><div class="input-unit"><input id="setting-${key}" type="number" data-setting="${key}" value="${draft[key]}" min="${key==='percent'||key==='drop'?1:0}" max="${max}" step="1">${unit}</div></div>`;}
function topField(key,label,values,helpText){return `<div class="setting-field"><label for="setting-${key}">${label} ${tip(helpText)}</label><select id="setting-${key}" data-setting="${key}">${values.map(n=>opt(n,`ТОП-${n}`,draft[key])).join('')}</select></div>`;}
function dirty(){return JSON.stringify(draft)!==JSON.stringify(state.settings);}
function settings(){return `<div class="settings-banner"><div class="flex" style="gap:17px"><div class="project-icon">G</div><div><div style="font-size:10px;letter-spacing:2px;color:#8d7c9f;margin-bottom:9px">Настройки проекта</div><h1>don-gabion.ru</h1><span class="secondary purple">https://don-gabion.ru/</span></div></div><div class="flex">${badge('Активен','green','check')}${badge('Мониторинг позиций и TR','purple','chart')}</div></div><section class="data-panel"><nav class="settings-tabs" aria-label="Настройки проекта"><span class="settings-tab">${icon('home')}Общая информация</span><span class="settings-tab">${icon('tag')}Регионы и поисковые системы</span><span class="settings-tab">${icon('folder')}Блоки тегов</span><span class="settings-tab">${icon('settings')}Тегирование / анализ страницы</span><span class="settings-tab">${icon('search')}Сбор позиций</span><span class="settings-tab active">${icon('chart')}Мониторинг позиций и TR</span></nav><div class="settings-content"><div class="settings-title"><h2>Мониторинг позиций и TR</h2><button class="link-button small" data-nav="dashboard">К просадкам и релевантности ${icon('arrow')}</button></div>${help()}<form class="settings-form" id="settings-form" novalidate>
<section class="settings-block"><div class="settings-block-header"><div><div class="section-label">Проверка после каждого сбора</div><h3>Мониторинг позиций ${tip('Включает автоматическую проверку условий мониторинга после каждого ручного или планового сбора позиций.')}</h3><p class="description">Выявляйте просадки позиций и проверяйте текстовую релевантность страниц.</p></div>${toggle('enabled','Мониторинг позиций')}</div>${!draft.enabled?'<div class="formula">Обычный сбор позиций продолжает работать. Условия мониторинга не проверяются, события не создаются, TR автоматически не запускается.</div>':''}${dev('включение мониторинга','<p>По умолчанию на демонстрационном проекте мониторинг включён. Первый переход OFF → ON автоматически запускает первоначальный TR всех объектов с определёнными Главным запросом, Relevant URL, ПС и регионом, даже при ручном режиме дальнейших запусков.</p><p>Повторное включение не стирает историю и не запускает первоначальные анализы заново. Выключение не отменяет уже начатый TR. Ручной запуск доступен. Для проверки первого включения используйте «Сценарии прототипа».</p>')}</section>
<section class="settings-block"><div class="section-label">Условие A</div><h3>Целевое состояние Группы</h3><p class="description">Одинаковое правило для всех Групп и каждого набора «Без группы» по Relevant URL.</p><div class="setting-fields">${topField('top','Запросов в',[3,5,10,20,30],'После сбора система считает все запросы Группы внутри выбранного ТОПа, включая Главный и Приоритетные.')}${numberField('percent','Должно быть не менее','После каждого сбора система рассчитывает, какая доля всех запросов Группы находится внутри выбранного ТОПа. Если значение ниже установленного процента, создаётся событие мониторинга.','%')}</div><div class="formula"><strong>Запросы в ТОП-${draft.top} / Все запросы × 100%</strong><br><span class="green">12 из 20 = 60% — условие выполнено при цели 60%.</span> <span>11 из 20 = 55% — условие нарушено.</span></div>${dev('логика контроля Группы','<p>1. Получить актуальные запросы Группы. 2. Посчитать позиции от 1 до выбранного ТОПа включительно. 3. Рассчитать точный процент. 4. Сравнить с порогом. 5. Если процент меньше порога — условие A нарушено. Равенство порогу — норма.</p><p>Главные, Приоритетные и обычные запросы равноправно участвуют в знаменателе. Не найденный запрос не входит в числитель. Пустой набор не создаёт сигнал.</p><p>Изменение состава Группы само по себе не создаёт событие мониторинга. Условие проверяется только на основании фактически собранных позиций актуального состава запросов.</p>')}${dev('запросы «Без группы»','<p>Источник — запросы без groupId. Только для мониторинга они группируются по одинаковому Relevant URL. Каждый URL — отдельный аналитический набор с отдельной долей, Главным запросом, историей и событием. Реальные Группы в проекте не создаются.</p><p>Главный запрос выбирается по максимальной !точной частотности набора. При её отсутствии — локальное предупреждение и пропуск автоматического TR только этого URL.</p>')}</section>
<section class="settings-block"><div class="settings-block-header"><div><div class="section-label">Условие B</div><h3>Отслеживание приоритетных запросов ${tip('Добавляет индивидуальное условие к проверке доли запросов Группы. Достаточно нарушения любого из двух условий.')}</h3><p class="description">Приоритетные запросы отмечаются звёздочкой в таблице позиций.</p></div>${toggle('priorities','Отслеживание приоритетных запросов')}</div>${draft.priorities?`<div class="setting-fields">${numberField('drop','Допустимое снижение','Если Приоритетный запрос до текущего сбора находился внутри выбранного диапазона и снизился не менее чем на указанное число позиций, условие мониторинга считается выполненным.','позиции')}${topField('priorityTop','Порог индивидуального отслеживания',[10,20,30],'Ограничивает только контроль изменения позиции Приоритетных запросов. Приоритетные запросы за пределами выбранного диапазона продолжают участвовать в общей статистике Группы.')}</div><div class="formula">При снижении ≥3 и пороге ТОП-20: <strong>5 → 8</strong> и <strong>18 → 24</strong> создают сигнал; <strong>27 → 31</strong> — нет.<br>Все приоритетные запросы продолжают участвовать в общей статистике Группы.</div>`:''}${dev('индивидуальный контроль','<p>Условие B: priority = true И previousPosition ≤ priorityTop И currentPosition − previousPosition ≥ drop. Границы включены. Если прежней позиции нет, индивидуальное сравнение не выполняется. Если запрос пропал из выдачи, он считается вышедшим за пределы наблюдаемой зоны и создаёт сигнал при известной прежней позиции в ней.</p><p>A и B независимы. Если нарушены оба, причины объединяются в одно уведомление и один запуск TR на объект и сбор. Нет сглаживания и ожидания нескольких сборов. По умолчанию: снижение ≥3, предыдущая позиция в ТОП-20.</p>')}</section>
<section class="settings-block"><div class="section-label">Диагностика просадки</div><h3>Запуск анализа текстовой релевантности</h3><p class="description">Уведомление создаётся по факту нарушения позиций. TR помогает оценить состояние страницы.</p><div class="radios"><label class="radio-label"><input type="radio" name="tr-mode" data-setting="mode" value="auto" ${draft.mode==='auto'?'checked':''}>Автоматический анализ TR ${tip('При нарушении условий мониторинга новый анализ TR запускается автоматически.')}</label><label class="radio-label"><input type="radio" name="tr-mode" data-setting="mode" value="manual" ${draft.mode==='manual'?'checked':''}>Только ручной анализ TR ${tip('Система фиксирует нарушение и создаёт уведомление, но новый анализ TR запускается SEO-специалистом вручную.')}</label></div><div class="formula">${draft.mode==='auto'?'После каждого сбора с нарушением TR запускается по Главному запросу и его Relevant URL в выбранной ПС и регионе.':'После сбора с нарушением появится оранжевая кнопка «Запустить анализ TR». Предыдущий анализ можно открыть через стрелку рядом.'}</div>${dev('режимы запуска и split button','<p>Автоматический режим: событие → Главный запрос → Relevant URL → TR с текущими ПС и регионом. Ручной режим: событие → needsAnalysis = true; запуска нет до нажатия основной части кнопки.</p><p>Состояния: требуется новый анализ — оранжевый; выполняется — основная кнопка заблокирована, dropdown открывает предыдущий; завершён — «Открыть анализ TR». При отсутствии прежнего результата соответствующее действие недоступно.</p><p>Каждый сбор с нарушением планирует новый запуск. Если TR уже выполняется, новый добавляется в очередь. Повторный клик не дублирует ручной запуск. При первом включении первоначальный анализ выполняется в любом режиме.</p>')}</section>
<section class="settings-block"><div class="section-label">Оценка результатов</div><h3>Целевой уровень текстовой релевантности ${tip('Используется для оценки текущего состояния страницы. Новый результат также сравнивается с предыдущим анализом для отображения динамики.')}</h3><p class="description">Страница соответствует целевому уровню, только если достигнуты все три значения.</p><div class="setting-fields">${numberField('general','Общая релевантность','Общая релевантность — среднее Ширины и Глубины. Для соответствия цели этот показатель должен быть не ниже заданного.','из 100')}${numberField('width','Ширина','Цель для показателя Ширины. Достижение цели по Общей релевантности не отменяет отдельную проверку Ширины.','из 100')}${numberField('depth','Глубина','Цель для показателя Глубины. Все три цели проверяются независимо, по текущему результату TR.','из 100')}</div><div class="formula">Общая релевантность = (Ширина + Глубина) / 2. Допустимые значения: 0–100.</div>${dev('оценка и динамика TR','<p>Дефолтные цели: общая 70, ширина 60, глубина 60. Если хотя бы один показатель ниже цели, статус — «Ниже целевого уровня». Смена целей пересчитывает статус существующих результатов, но не создаёт событие и не запускает TR.</p><p>Δ = текущий результат − непосредственно предыдущий. Без категорий значимости: положительная динамика зелёная, отрицательная приглушённо-красная, нулевая нейтральная. В первом анализе Предыдущий и Δ равны «—».</p>')}</section></form></div><footer class="savebar"><span id="save-status" class="small ${dirty()?'unsaved':''}">${dirty()?'Есть несохранённые изменения':'Настройки сохранены в этом браузере'}</span><div class="flex"><button class="btn outline" data-action="reset-settings">Сбросить изменения</button><button class="btn primary" data-action="save-settings">Сохранить</button></div></footer></section>`;}
function render(){const openDetails=[...document.querySelectorAll('details[open]')].map(el=>el.id).filter(Boolean);tooltipOff();$('#portal').innerHTML='';$('#app').innerHTML=shell(page==='settings'?settings():page==='positions'?positions():dashboard());for(const id of openDetails){const el=document.getElementById(id);if(el)el.open=true;}document.title=`${page==='settings'?'Настройки мониторинга':page==='positions'?'Позиции':'Просадки и релевантность'} — Webtronica`;}
function refreshTable(){const container=$('#table-content');if(container)container.innerHTML=page==='positions'?positionsTable():dashboardTable(filteredObjects());}
function navigate(next){page=next;pageNumber=1;render();window.scrollTo({top:0,behavior:'instant'});}
function dialog(title,body,footer='',subtitle=''){modalReturnFocus=document.activeElement;$('#overlay').innerHTML=`<div class="modal-backdrop" data-dismiss="modal"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title" tabindex="-1"><header class="modal-header"><div><h2 id="dialog-title">${title}</h2>${subtitle?`<p class="secondary">${subtitle}</p>`:''}</div><button class="icon-btn" data-action="close-modal" aria-label="Закрыть">${icon('close')}</button></header><div class="modal-content">${body}</div>${footer?`<footer class="modal-footer">${footer}</footer>`:''}</section></div>`;document.body.style.overflow='hidden';$('.modal').focus();}
function closeModal(){$('#overlay').innerHTML='';document.body.style.overflow='';if(modalReturnFocus?.isConnected)modalReturnFocus.focus();}
function menu(anchor,items){const r=anchor.getBoundingClientRect();$('#portal').innerHTML=`<div class="menu portal-menu" role="menu">${items}</div>`;const el=$('.portal-menu');const h=el.getBoundingClientRect().height;el.style.left=Math.max(8,Math.min(r.right-el.offsetWidth,window.innerWidth-el.offsetWidth-8))+'px';el.style.top=(r.bottom+h+8>window.innerHeight?Math.max(8,r.top-h-5):r.bottom+5)+'px';el.querySelector('button:not(:disabled)')?.focus();}
function fullTRButton(result){
  // The TR module supplies the URL for this specific historical result.
  // Demo records use the example URL supplied for this prototype.
  // Relevant URL is the analysed page, never the destination of this action.
  let href='';
  const destination=result.fullAnalysisUrl||'https://webtronica.io/dashboard/text-relevance-analysis/72?projectId=61';
  if(destination){
    try{const url=new URL(destination,location.href);if(['https:','http:'].includes(url.protocol))href=url.href;}catch{}
  }
  const label=`Полный анализ TR ${icon('external')}`;
  return href
    ? `<a class="btn outline full-tr-link" href="${esc(href)}" target="_blank" rel="noopener noreferrer" aria-label="Полный анализ TR — открыть в новой вкладке" title="Открыть полный анализ в модуле «Анализ TR»">${label}</a>`
    : `<button type="button" class="btn outline full-tr-link" disabled title="Ссылка на полный анализ пока не указана для этого результата" aria-label="Полный анализ TR — ссылка пока не указана">${label}</button>`;
}
function openTR(o,index=o.analyses.length-1){if(!o.analyses.length){toast('Для этого объекта пока нет результатов TR.');return;}const r=o.analyses[index];const below=M.total(r)<state.settings.general||r.width<state.settings.width||r.depth<state.settings.depth;dialog('Анализ текстовой релевантности',`<div class="analysis-meta"><div><span>Главный запрос на момент анализа</span><strong>${esc(r.query)}</strong></div><div><span>Relevant URL</span><span class="purple" style="font-size:13px">https://don-gabion.ru${esc(r.url)}</span></div><div><span>Поисковая система и регион</span>${esc(r.engine)} · ${esc(r.region)}</div><div><span>Дата анализа</span>${r.date}</div></div>${badge(below?'Ниже целевого уровня':'Соответствует целевому уровню',below?'orange':'green',below?'warning':'check')}<div style="margin-top:17px">${trTable(o,index)}</div><p class="analysis-description">Общая релевантность = (Ширина + Глубина) / 2. Результат сравнивается с непосредственно предыдущим анализом и текущими целями проекта.</p><div class="history-list"><h3 style="margin-bottom:9px">Анализы страницы</h3>${o.analyses.map((a,i)=>`<button data-action="analysis-version" data-id="${o.id}" data-index="${i}"><span>${a.date} ${i===index?'· открыт':''}</span><span>Общая ${fmt(M.total(a))} ${icon('right')}</span></button>`).reverse().join('')}</div>`,`${fullTRButton(r)}<div class="flex"><button class="btn outline" data-action="close-modal">Закрыть</button><button class="btn primary" data-action="run-tr-modal" data-id="${o.id}" ${o.trState==='running'||!M.mainQuery(o)?'disabled':''}>${icon('refresh')}Новый анализ TR</button></div>`,esc(description(o)));}
function missing(o){dialog('Главный запрос не определён',missingWarning(o),'',esc(description(o)));}
function notifications(){modalReturnFocus=document.activeElement;$('#overlay').innerHTML=`<div class="sidepanel-backdrop" data-dismiss="modal"><section class="sidepanel" role="dialog" aria-modal="true" aria-labelledby="events-title" tabindex="-1"><header class="sidepanel-header"><div><h2 id="events-title">События Webtronica</h2><p class="secondary">Мониторинг позиций · ${state.events.length} событий</p></div><button class="icon-btn" data-action="close-modal" aria-label="Закрыть">${icon('close')}</button></header><div style="padding:13px 22px;border-bottom:1px solid var(--line)" class="flex space"><span class="small muted">${state.context.engine} · ${state.context.region}</span><button class="link-button small" data-action="read-events">Прочитать все</button></div><div class="events-list">${state.events.length?state.events.map(e=>`<article class="event-item"><span class="event-date">${e.date}${!e.read?' · новое':''}</span><h3>${esc(e.name)}</h3>${badge('Нарушено условие мониторинга','orange','warning')}<div class="event-reasons">${e.reasons.map(r=>`<p>${esc(r)}</p>`).join('')}</div><button class="link-button small" data-action="event-object" data-id="${e.objectId}" data-event="${e.id}">Открыть объект ${icon('arrow')}</button></article>`).join(''):'<div class="empty">Новых событий нет.<br>Уведомления появятся после сбора с нарушением условий.</div>'}</div><div style="padding:16px 22px;background:var(--bg);font-size:11px;line-height:1.6;color:var(--muted)">Событие создаётся при нарушении позиций. Результат TR используется для диагностики и не создаёт отдельного уведомления.</div></section></div>`;document.body.style.overflow='hidden';$('.sidepanel').focus();}
function demoDialog(){dialog('Сценарии прототипа',`<p class="muted small" style="line-height:1.7;margin-bottom:20px">Выберите сценарий для проверки интерфейса. Данные локальные, запросы к Webtronica не отправляются. Перезапуск сценария восстановит демонстрационные настройки, позиции и историю.</p><div class="quick-scenarios"><button class="btn outline" data-action="demo-reset">${icon('layers')} Все состояния — основной сценарий</button><p class="secondary" style="margin:0 0 10px 25px">68% в норме · 52% ниже цели · 65% и приоритетный сигнал · оба условия · ручной Главный · TR выполняется · нет частотности</p><button class="btn outline" data-action="demo-first">${icon('play')} Первое включение мониторинга</button><p class="secondary" style="margin:0 0 10px 25px">Мониторинг выключен, анализов нет. Включите и сохраните — первоначальный TR запустится автоматически.</p><button class="btn outline" data-action="demo-auto">${icon('refresh')} Автоматический TR после нового сбора</button><p class="secondary" style="margin:0 0 0 25px">Будет выполнен сбор, созданы события и запущены анализы всех подходящих объектов с нарушениями.</p></div>`,`<span class="muted small">Сценарии можно повторять</span><button class="btn primary" data-action="close-modal">Вернуться</button>`);}
function demoTime(extra=0,owner=state){const base=new Date('2026-09-27T09:00:00');base.setMinutes(base.getMinutes()+owner.collections.length+extra);return `${String(base.getDate()).padStart(2,'0')}.${String(base.getMonth()+1).padStart(2,'0')}.${base.getFullYear()} ${String(base.getHours()).padStart(2,'0')}:${String(base.getMinutes()).padStart(2,'0')}`;}
function schedule(o,delay=4200,owner=state){const key=`${owner.context.engine}|${owner.context.region}|${o.id}`;if(timers.has(key))return;timers.set(key,setTimeout(()=>{timers.delete(key);if(o.trState!=='running')return;M.finishAnalysis(o,demoTime(1,owner));persist();if(state===owner){render();toast(`TR завершён: ${description(o)}`);}if(o.trState==='running')schedule(o,4200,owner);},delay));}
function runTR(o){if(o.trState==='running')return;if(!M.eligible(o,state.context)){missing(o);return;}o.pendingManualCollection=false;o.trState='running';o.run={kind:'manual',date:demoTime(),query:M.mainQuery(o).text,url:M.mainQuery(o).url,engine:state.context.engine,region:state.context.region};const latest=o.checks[0];if(latest?.violated&&o.needsAnalysis){o.run.collectionId=latest.id.slice(0,latest.id.lastIndexOf(':'));latest.tr='TR запущен вручную';}persist();render();schedule(o);toast(`Анализ запущен: ${description(o)}`);}
function saveSettings(){const error=M.validate(draft);if(error){toast(error,true);return;}const first=draft.enabled&&!state.initialized;state.settings=M.clone(draft);for(const p of Object.values(pool))p.settings=M.clone(draft);const jobs=M.initialJobs(state,demoTime());persist();render();jobs.forEach(id=>schedule(getObject(id),4200));toast(first?`Мониторинг включён. Первоначальных анализов TR запущено: ${jobs.length}. Объекты без частотности пропущены.`:'Настройки сохранены. Условия будут проверены после следующего сбора.');}
function collectPositions(){if(collecting)return;collecting=true;render();const owner=state;setTimeout(()=>{collecting=false;const date=demoTime(1);owner.hasPositions=true;const n=owner.collections.length;for(const o of owner.objects)for(const q of o.queries){q.previous=q.position;if(q.position!==null){const direction=n%2===0?1:-1;const amount=q.priority?3:0;q.position=Math.max(1,Math.min(100,q.position+direction*amount));}}const initial=M.initialJobs(owner,date);const result=M.collect(owner,date,`collection-${Date.now()}-${owner.collections.length}`);persist();if(state===owner){render();toast(owner.settings.enabled?`Позиции собраны. Событий: ${result.events.length}. ${owner.settings.mode==='auto'?`TR запланирован для ${owner.objects.filter(o=>M.evaluate(o,owner.settings).violated&&M.eligible(o,owner.context)).length} объектов.`:'TR запускается вручную.'}`:'Позиции собраны. Мониторинг выключен — новых событий нет.');}for(const id of [...new Set([...initial,...result.jobs])])schedule(owner.objects.find(o=>o.id===id),5000,owner);},1100);}
function resetDemo(kind){for(const t of timers.values())clearTimeout(t);timers.clear();state=M.createDemo(kind!=='first');pool={};draft=M.clone(state.settings);expanded.clear();filters={folder:'all',group:'all',url:'all',monitor:'all',tr:'all',search:'',from:'2026-09-01',to:'2026-09-27'};closeModal();page=kind==='first'?'settings':'dashboard';if(kind==='auto'){state.settings.mode='auto';draft=M.clone(state.settings);}persist();render();state.objects.filter(o=>o.trState==='running').forEach(o=>schedule(o,kind==='auto'?6000:30000));if(kind==='auto')collectPositions();}
function changeContext(key,value){const oldKey=`${state.context.engine}|${state.context.region}`;pool[oldKey]=state;const nextContext={...state.context,[key]:value};const nextKey=`${nextContext.engine}|${nextContext.region}`;const shared=M.clone(state.settings);if(pool[nextKey]){state=pool[nextKey];delete pool[nextKey];}else{state=M.createDemo(false);state.context=nextContext;state.hasPositions=false;state.lastCollection=null;}state.settings=shared;draft=M.clone(shared);expanded.clear();filters.group='all';filters.url='all';filters.folder='all';persist();render();}
document.addEventListener('click',e=>{
const el=e.target.closest('[data-action],[data-nav],[data-dismiss]');
if(!e.target.closest('.portal-menu')&&!e.target.closest('[data-action="tr-menu"],[data-action="query-menu"]'))$('#portal').innerHTML='';
if(!el){const row=e.target.closest('[data-row]');if(row&&!e.target.closest('button,input,select,a')){expanded.has(row.dataset.row)?expanded.delete(row.dataset.row):expanded.add(row.dataset.row);render();}return;}
if(el.dataset.nav){navigate(el.dataset.nav);return;}
if(el.dataset.dismiss){if(e.target===el)closeModal();return;}
const action=el.dataset.action,o=el.dataset.id?getObject(el.dataset.id):null,q=o?.queries.find(q=>q.id===el.dataset.query);
switch(action){
case 'expand':expanded.has(o.id)?expanded.delete(o.id):expanded.add(o.id);render();break;
case 'help':{const h=$('#how-it-works');h.open=!h.open;h.scrollIntoView({behavior:'smooth',block:'start'});break;}
case 'collect':collectPositions();break;
case 'save-settings':saveSettings();break;
case 'reset-settings':draft=M.clone(state.settings);render();toast('Несохранённые изменения сброшены.');break;
case 'notifications':notifications();break;
case 'close-modal':closeModal();break;
case 'read-events':state.events.forEach(e=>e.read=true);persist();render();notifications();break;
case 'event-object':{const ev=state.events.find(v=>v.id===el.dataset.event);if(ev)ev.read=true;closeModal();filters={...filters,folder:'all',group:o.type==='group'?o.id:'ungrouped',url:o.queries[0].url,monitor:'all',tr:'all',search:'',from:'',to:''};expanded.add(o.id);persist();navigate('dashboard');break;}
case 'reset-filters':filters={folder:'all',group:'all',url:'all',monitor:'all',tr:'all',search:'',from:'2026-09-01',to:'2026-09-27'};pageNumber=1;render();break;
case 'filter-url':filters.url=el.dataset.url;render();break;
case 'missing':missing(o);break;
case 'object-positions':closeModal();filters={...filters,folder:'all',group:o.type==='group'?o.id:'ungrouped',url:o.queries[0].url,search:'',monitor:'all',tr:'all',from:'',to:''};navigate('positions');break;
case 'priority':q.priority=!q.priority;persist();render();toast(q.priority?'Запрос отмечен как Приоритетный.':'Приоритет снят. Запрос по-прежнему участвует в статистике Группы.');break;
case 'query-menu':menu(el,`${o.type==='group'?`<button role="menuitem" data-action="set-main" data-id="${o.id}" data-query="${q.id}" ${o.manualMain===q.id?'disabled':''}>${icon('crown')}Сделать Главным запросом</button><button role="menuitem" data-action="auto-main" data-id="${o.id}" ${!o.manualMain?'disabled':''}>${icon('refresh')}Вернуть автоматический выбор</button>`:`<button role="menuitem" disabled>Главный определяется по Relevant URL</button>`}<button role="menuitem" data-action="priority" data-id="${o.id}" data-query="${q.id}">${icon('star')}${q.priority?'Снять приоритет':'Отметить Приоритетным'}</button>`);break;
case 'set-main':if(o.type==='group'){o.manualMain=q.id;persist();render();toast(`Главный запрос выбран вручную: ${q.text}`);}break;
case 'auto-main':o.manualMain=null;persist();render();toast(M.mainQuery(o)?`Автоматический выбор: ${M.mainQuery(o).text}`:'Автовыбор включён. Заполните !точную частотность.');break;
case 'tr-menu':menu(el,`<button role="menuitem" data-action="open-tr" data-id="${o.id}" ${!o.analyses.length?'disabled':''}>${icon('external')}${o.trState==='running'?'Открыть предыдущий анализ TR':'Открыть анализ TR'}</button><button role="menuitem" data-action="run-tr" data-id="${o.id}" ${o.trState==='running'||!M.mainQuery(o)?'disabled':''}>${icon('refresh')}Запустить новый анализ TR</button><button role="menuitem" data-action="history" data-id="${o.id}">${icon('clock')}История проверок</button>`);break;
case 'open-tr':openTR(o);break;
case 'analysis-version':openTR(o,Number(el.dataset.index));break;
case 'run-tr':runTR(o);break;
case 'run-tr-modal':closeModal();runTR(o);break;
case 'history':dialog('История проверок',history(o),`<span class="muted small">Каждый сбор — отдельная контрольная точка</span><button class="btn outline" data-action="close-modal">Закрыть</button>`,esc(description(o)));break;
case 'prev-page':pageNumber--;refreshTable();break;
case 'next-page':pageNumber++;refreshTable();break;
case 'demo':demoDialog();break;
case 'demo-reset':resetDemo('all');break;
case 'demo-first':resetDemo('first');break;
case 'demo-auto':resetDemo('auto');break;
}
});
document.addEventListener('input',e=>{if(e.target.id==='search'){filters.search=e.target.value;pageNumber=1;refreshTable();}if(e.target.dataset.setting&&e.target.type==='number'){draft[e.target.dataset.setting]=e.target.value===''?NaN:Number(e.target.value);const status=$('#save-status');if(status){status.textContent='Есть несохранённые изменения';status.classList.add('unsaved');}}});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.filter){const old=filters[el.dataset.filter];filters[el.dataset.filter]=el.value;if(filters.from&&filters.to&&filters.from>filters.to){filters[el.dataset.filter]=old;el.value=old;toast('Начало периода не может быть позже окончания.',true);return;}pageNumber=1;render();}else if(el.dataset.context){changeContext(el.dataset.context,el.value);}else if(el.dataset.setting){draft[el.dataset.setting]=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?NaN:Number(el.value)):el.tagName==='SELECT'?Number(el.value):el.value;if(el.type!=='number')render();}else if(el.dataset.frequency){const o=getObject(el.dataset.id),q=o.queries.find(q=>q.id===el.dataset.frequency);const value=el.value===''?null:Number(el.value);if(value!==null&&(!Number.isSafeInteger(value)||value<0)){el.value=q.frequency??'';toast('Введите целую неотрицательную частотность или оставьте поле пустым.',true);return;}q.frequency=value;persist();render();toast('!точная частотность обновлена.');}});
document.addEventListener('submit',e=>{if(e.target.id==='settings-form'){e.preventDefault();saveSettings();}});
function showTooltip(el){const r=el.getBoundingClientRect(),t=$('#tooltip');t.textContent=el.dataset.tip;t.hidden=false;const w=t.offsetWidth,h=t.offsetHeight;t.style.left=Math.max(8,Math.min(r.left,window.innerWidth-w-8))+'px';t.style.top=(r.bottom+h+12>window.innerHeight?Math.max(8,r.top-h-8):r.bottom+8)+'px';}
document.addEventListener('mouseover',e=>{const el=e.target.closest('[data-tip]');if(el)showTooltip(el);});
document.addEventListener('mouseout',e=>{if(e.target.closest('[data-tip]'))tooltipOff();});
document.addEventListener('focusin',e=>{if(e.target.dataset.tip)showTooltip(e.target);});
document.addEventListener('focusout',tooltipOff);
window.addEventListener('scroll',()=>{tooltipOff();$('#portal').innerHTML='';},{passive:true});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();$('#portal').innerHTML='';tooltipOff();}const dialogEl=$('[role="dialog"]');if(e.key==='Tab'&&dialogEl){const items=[...dialogEl.querySelectorAll('button:not(:disabled),input,select,a[href],[tabindex="0"]')].filter(x=>x.offsetParent!==null);if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialogEl)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}const menuEl=$('.portal-menu');if(menuEl&&['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const items=[...menuEl.querySelectorAll('button:not(:disabled)')];let i=items.indexOf(document.activeElement);i=(i+(e.key==='ArrowDown'?1:-1)+items.length)%items.length;items[i]?.focus();}});
render();
state.objects.filter(o=>o.trState==='running').forEach(o=>schedule(o,30000));
for(const p of Object.values(pool))p.objects.filter(o=>o.trState==='running').forEach(o=>schedule(o,5000,p));
})();


